<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Tue, 10 May 2016 14:01:57 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
